/**
 * ── Japanese Language Detection Utilities ─────────────────────────────────────
 *
 * Helpers for detecting whether page content or metadata is Japanese.
 * Used by both the text-tracker (overlay decisions) and video-tracker
 * (auto-queue filtering, badge visibility).
 */

import { JP_RE } from '../constants';

/**
 * Check if the current YouTube page is likely playing music content.
 * Used to suppress video tracking on music videos when `config.hideMusic` is enabled.
 *
 * Detection heuristics (in order of reliability):
 * 1. `music.youtube.com` host → always music
 * 2. YouTube `playerResponse.videoDetails.categoryId === "10"` (Music category)
 * 3. `<meta itemprop="genre" content="Music">` tag
 * 4. Music-specific renderer elements in the DOM
 * 5. "Auto-generated by YouTube" / "Provided to YouTube" text in description
 */
export function isMusic(): boolean {
  const host = window.location.hostname;
  if (host === 'music.youtube.com') return true;

  if (host.includes('youtube.com')) {
    const isLive = !!document.querySelector('.ytp-live, .re-live-badge, [is-live]');
    const hasMusicMetadata = !!document.querySelector('ytd-structured-description-content-renderer');
    const playerResponse = (window as any).ytInitialPlayerResponse;
    const isMusicCategory = playerResponse?.videoDetails?.categoryId === '10';

    if (isLive) return hasMusicMetadata;
    if (isMusicCategory) return true;

    const g = document.querySelector('meta[itemprop="genre"]');
    if (g?.getAttribute('content') === 'Music') return true;
    if (document.querySelector('ytd-music-watch-metadata-renderer')) return true;

    const secondaryInfo =
      (document.querySelector('ytd-video-secondary-info-renderer') as HTMLElement | null)?.innerText || '';
    if (secondaryInfo.includes('Auto-generated by YouTube') || secondaryInfo.includes('Provided to YouTube'))
      return true;
  }
  return false;
}

/**
 * Check if the current page is likely Japanese content.
 * Uses multiple signals: host-based checks, caption tracks, title/channel
 * Japanese character counts, and description sampling.
 *
 * Used by the video tracker to decide whether to auto-queue.
 */
export function isLikelyJapanese(): boolean {
  const host = window.location.hostname;

  /* Known Japanese content sites → always true */
  if (host.includes('animekai') || host.includes('crunchyroll')) return true;

  if (host.includes('youtube.com')) {
    /* Check for Japanese caption tracks in player response */
    try {
      const playerResponse = (window as any).ytInitialPlayerResponse;
      const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (tracks) {
        for (const track of tracks) if (track.languageCode === 'ja') return true;
      }
    } catch (_e) { /* caption data not available */ }

    /* Check document title for Japanese characters */
    const docTitle = document.title.replace(/^\(\d+\)\s*/, '');
    if ((docTitle.match(JP_RE) ?? []).length >= 1) return true;

    /* Check video title element */
    const titleEl = document.querySelector<HTMLElement>('#title h1 yt-formatted-string, h1.ytd-watch-metadata');
    if (titleEl && (titleEl.innerText.match(JP_RE) ?? []).length >= 1) return true;

    /* Check channel name */
    const channelEl = document.querySelector<HTMLElement>(
      '#owner ytd-channel-name yt-formatted-string, ytd-channel-name a',
    );
    if (channelEl && (channelEl.innerText.match(JP_RE) ?? []).length >= 1) return true;

    /* Sample the video description for Japanese text */
    const descEl = document.querySelector<HTMLElement>(
      '#description-inline-expander yt-attributed-string, ytd-expandable-video-description-body-renderer',
    );
    if (descEl) {
      const sample = descEl.innerText?.slice(0, 1000) ?? '';
      if ((sample.match(JP_RE) ?? []).length >= 3) return true;
    }
  }
  return false;
}

/**
 * Check if a page contains enough Japanese text to warrant showing the overlay.
 * Unlike `isLikelyJapanese()` which is YouTube-specific, this works on any page.
 *
 * Detection strategy:
 * 1. Check allow-list → instant yes
 * 2. If allowListOnly → instant no (skip auto-detection)
 * 3. Check `<html lang="ja">` → yes
 * 4. Wait 1.5s for page load, then sample body text for ≥40 JP characters
 *
 * @param config - Current tracker configuration
 * @param allowSitesDefault - Default allow list to use if config has none
 */
export async function isJapanesePage(
  config: { allowSites?: string[]; allowListOnly?: boolean },
  allowSitesDefault: readonly string[],
): Promise<boolean> {
  const host = window.location.hostname;
  const allowSites: string[] = config.allowSites ?? [...allowSitesDefault];
  const allowListOnly: boolean = config.allowListOnly ?? false;

  /* Allow-listed domains always show the overlay */
  if (allowSites.some((d: string) => host.includes(d))) return true;

  /* If strict mode, only allow-listed sites pass */
  if (allowListOnly) return false;

  /* Check the HTML lang attribute */
  const lang = document.documentElement.lang;
  if (lang.startsWith('ja')) return true;

  /* Wait for page content to load, then sample body text */
  await new Promise((r) => setTimeout(r, 1500));
  const sample = (document.body?.textContent ?? '').slice(0, 8000);
  const jpCount = (sample.match(JP_RE) ?? []).length;
  return jpCount >= 40;
}
