import { defineContentScript } from '#imports';
import { configStorage, videoQueueStorage } from '@/utils/storage';
import { resolveVideoChannelMedia, submitLog } from '@/utils/api';
import '@/assets/player.css';

const JP_RE = /[\u3040-\u30ff\u4e00-\u9fff]/g;

// ── Helpers ───────────────────────────────────────────────────────────────────
function fmtSecs(s: number): string {
  s = Math.floor(s);
  const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), sec = s % 60;
  const p = (n: number) => String(n).padStart(2, '0');
  return h > 0 ? `${h}:${p(m)}:${p(sec)}` : `${m}:${p(sec)}`;
}

function toast(msg: string, err = false) {
  const el = document.createElement('div');
  Object.assign(el.style, {
    position: 'fixed',
    bottom: '20px',
    right: '20px',
    zIndex: '2147483647',
    background: err ? '#1a0f0f' : '#0f1a0f',
    color: err ? '#f0706a' : '#3ddc84',
    border: `1px solid ${err ? 'rgba(240,112,106,.4)' : 'rgba(61,220,132,.4)'}`,
    borderRadius: '5px',
    padding: '9px 15px',
    fontFamily: "'Courier New',monospace",
    fontSize: '13px',
    boxShadow: '0 4px 20px rgba(0,0,0,.6)',
    writingMode: 'horizontal-tb',
    direction: 'ltr',
    textAlign: 'left',
    lineHeight: '1.4',
    pointerEvents: 'none',
  });
  el.textContent = msg;
  document.body.appendChild(el);
  setTimeout(() => {
    el.style.opacity = '0';
    el.style.transition = 'opacity 0.5s';
    setTimeout(() => el.remove(), 500);
  }, 3000);
}

if (typeof browser !== 'undefined' && browser.runtime?.onMessage) {
  browser.runtime.onMessage.addListener((req: any) => {
    if (req?.action === 'SHOW_TOAST') {
      const g = globalThis as any;
      if (!g.__nt_toastSink) g.__nt_toastSink = 'video';
      if (g.__nt_toastSink !== 'video') return;

      const title = String(req.title || '');
      const msg = req.message;
      const text = msg ? `${title}: ${msg}` : title;
      const isErr = title.toLowerCase().includes('fail') || title.toLowerCase().includes('error');
      toast(text, isErr);
    }
  });
}

function cleanUrl(url: string): string {
  try {
    const u = new URL(url);
    if (u.hostname.includes('youtube.com') || u.hostname.includes('youtu.be')) {
      const v = u.searchParams.get('v');
      if (v) return `https://www.youtube.com/watch?v=${v}`;
    }
    return u.origin + u.pathname;
  } catch { return url; }
}

function isMusic(): boolean {
  const host = window.location.hostname;
  if (host === 'music.youtube.com') return true;

  if (host.includes('youtube.com')) {
    // 1. Is it a Livestream?
    // Usually, "Music" categorization for a Live stream is a false positive for your needs.
    const isLive = !!document.querySelector('.ytp-live, .re-live-badge, [is-live]');

    // 2. Check for "Song" metadata in the description
    // This is the "Music in this video" section that YouTube generates.
    // It's almost never present on a standard "Just Chatting" livestream.
    const hasMusicMetadata = !!document.querySelector('ytd-structured-description-content-renderer');

    // 3. Official Category ID (10 = Music)
    const playerResponse = (window as any).ytInitialPlayerResponse;
    const isMusicCategory = playerResponse?.videoDetails?.categoryId === "10";

    // 4. Logic Gate:
    // If it's a Live stream, we ONLY count it as music if it has official music metadata
    // (which occasionally happens for 24/7 radio stations).
    // Otherwise, we treat Live as "Not Music" to avoid the VTuber/Chatting trap.
    if (isLive) {
      return hasMusicMetadata;
    }

    // For non-live videos:
    if (isMusicCategory) return true;

    const g = document.querySelector('meta[itemprop="genre"]');
    if (g?.getAttribute('content') === 'Music') return true;

    if (document.querySelector('ytd-music-watch-metadata-renderer')) return true;

    // Check for "Topic" channels or Auto-generated Art Tracks
    const secondaryInfo = (document.querySelector('ytd-video-secondary-info-renderer') as HTMLElement | null)?.innerText || '';
    if (secondaryInfo.includes('Auto-generated by YouTube') ||
      secondaryInfo.includes('Provided to YouTube')) {
      return true;
      }
  }
  return false;
}

// ── Robust JP detection ───────────────────────────────────────────────────────
function isLikelyJapanese(): boolean {
  const host = window.location.hostname;
  if (host.includes('animekai') || host.includes('crunchyroll')) return true;

  if (host.includes('youtube.com')) {
    // 1. NEW: Check YouTube's internal player data for Japanese captions (Auto or Manual)
    // This catches videos where the title is in English, but the audio is Japanese.
    try {
      // Use any cast if in TypeScript to avoid window object errors
      const playerResponse = (window as any).ytInitialPlayerResponse;
      const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (tracks) {
        for (const track of tracks) {
          // If any subtitle track is in Japanese, flag it as true immediately
          if (track.languageCode === 'ja') return true;
        }
      }
    } catch (e) {
      // Silently fail and fall back to DOM scraping if object is unavailable
    }

    // 2. Check Document Title (SPA updates this reliably)
    const docTitle = document.title.replace(/^\(\d+\)\s*/, '');
    if ((docTitle.match(JP_RE) ??[]).length >= 1) return true;

    // 3. Check Video Title Element
    const titleEl = document.querySelector<HTMLElement>('#title h1 yt-formatted-string, h1.ytd-watch-metadata');
    if (titleEl && (titleEl.innerText.match(JP_RE) ??[]).length >= 1) return true;

    // 4. Check Channel Name
    const channelEl = document.querySelector<HTMLElement>('#owner ytd-channel-name yt-formatted-string, ytd-channel-name a');
    if (channelEl && (channelEl.innerText.match(JP_RE) ??[]).length >= 1) return true;

    // 5. Check Description
    const descEl = document.querySelector<HTMLElement>('#description-inline-expander yt-attributed-string, ytd-expandable-video-description-body-renderer');
    if (descEl) {
      const sample = descEl.innerText?.slice(0, 1000) ?? '';
      if ((sample.match(JP_RE) ??[]).length >= 3) return true;
    }

    return false;
  }
  return false;
}

let _jpCacheUrl = '';
let _jpCacheResult = false;
function isLikelyJapaneseCached(): boolean {
  const url = cleanUrl(window.location.href);
  if (url !== _jpCacheUrl || !_jpCacheResult) {
    _jpCacheResult = isLikelyJapanese();
    _jpCacheUrl = url;
  }
  return _jpCacheResult;
}
function invalidateJpCache() { _jpCacheUrl = ''; _jpCacheResult = false; }

// ── Channel ID & Name ─────────────────────────────────────────────────────────
function getYouTubeChannelId(): string | null {
  for (const s of document.querySelectorAll('script:not([src])')) {
    const m = s.textContent?.match(/"channelId"\s*:\s*"(UC[a-zA-Z0-9_-]{22})"/);
    if (m) return m[1];
  }
  const link = document.querySelector<HTMLLinkElement>('link[itemprop="url"][href*="/channel/"]');
  if (link) { const m = link.href.match(/\/channel\/(UC[a-zA-Z0-9_-]{22})/); if (m) return m[1]; }
  const a = document.querySelector<HTMLAnchorElement>('ytd-channel-name a[href*="/channel/"]');
  if (a) { const m = a.href.match(/\/channel\/(UC[a-zA-Z0-9_-]{22})/); if (m) return m[1]; }
  return null;
}

function getChannelNameFallback(): string {
  const ytEl = document.querySelector<HTMLElement>('ytd-channel-name yt-formatted-string, ytd-channel-name a');
  if (ytEl?.innerText?.trim()) return ytEl.innerText.trim();
  const showEl = document.querySelector<HTMLElement>('.show-title-link, .series-title, .title[data-t="title"]');
  if (showEl?.innerText?.trim()) return showEl.innerText.trim();
  return '';
}

const channelMediaCache: Record<string, any> = {};
async function getChannelMediaData(channelId: string | null, fallbackTitle = '') {
  const key = channelId || `title:${fallbackTitle}`;
  if (channelMediaCache[key]) return channelMediaCache[key];

  let media: any = {};
  try {
    media = await resolveVideoChannelMedia({ channelId: channelId || undefined, channelTitle: fallbackTitle || undefined });
  } catch {
    media = {};
  }

  const normalized = {
    channelId: channelId || media.channelId || 'web-video',
    channelTitle: media.channelTitle || fallbackTitle,
    ...(media.channelImage ? { channelImage: media.channelImage } : {}),
    ...(media.channelDescription ? { channelDescription: media.channelDescription } : {}),
  };
  channelMediaCache[key] = normalized;
  return normalized;
}

function reachedQueueThreshold(cfg: any, liveSecs: number, vid: HTMLVideoElement): boolean {
  const tType = cfg.queueThresholdType ?? 'time';
  const tValue = cfg.queueThresholdValue ?? 1;
  if (tType === 'percent') {
    if (!vid.duration || vid.duration <= 0) return false;
    return (vid.currentTime / vid.duration) * 100 >= tValue;
  }
  return (liveSecs / 60) >= tValue;
}

// ── Queue helpers ─────────────────────────────────────────────────────────────
async function upsertQueueLive(secs: number, videoTitle: string, channelName: string, url: string, channelId: string | null, sessionId: string) {
  const clean = cleanUrl(url);
  const queue = await videoQueueStorage.getValue();
  const idx = queue.findIndex(q => q.contentTitleEnglish === clean);
  const mediaData = await getChannelMediaData(channelId, channelName);

  if (idx !== -1) {
    const item = queue[idx] as any;
    item.sessions = item.sessions ||[];

    const sIdx = item.sessions.findIndex((s: any) => s.id === sessionId);
    if (sIdx >= 0) {
      item.sessions[sIdx].secs = secs;
      item.sessions[sIdx].date = new Date().toISOString();
    } else {
      item.sessions.push({ id: sessionId, secs, date: new Date().toISOString() });
    }

    const completedSecs = item.sessions.reduce((a: number, s: any) => a + s.secs, 0);
    item.time = Math.max(1, Math.round(completedSecs / 60));
    item.description = videoTitle;
    item.contentTitleNative = channelName;
    if (channelId && !item.channelId) item.channelId = channelId;
    item.mediaData = {
      ...(item.mediaData || {}),
      ...mediaData,
    };
    delete item._currentSecs;
  } else {
    queue.push({
      id: crypto.randomUUID(),
               contentTitleNative: channelName,
               contentTitleEnglish: clean,
               time: Math.max(1, Math.round(secs / 60)),
               date: new Date().toISOString(),
               private: false, tags: [],
                 description: videoTitle,
                 sessions:[{ id: sessionId, secs, date: new Date().toISOString() }],
               channelId,
                 mediaData,
    } as any);
  }
  await videoQueueStorage.setValue([...queue]);
  try { browser.runtime.sendMessage({ action: 'QUEUE_UPDATED', count: queue.length }); } catch {}
}

async function finalizeSession(secs: number, url: string, sessionId: string) {
  if (secs < 1) return;
  const clean = cleanUrl(url);
  const queue = await videoQueueStorage.getValue();
  const idx = queue.findIndex(q => q.contentTitleEnglish === clean);
  if (idx === -1) return;

  const item = queue[idx] as any;
  item.sessions = item.sessions ||[];

  const sIdx = item.sessions.findIndex((s: any) => s.id === sessionId);
  if (sIdx >= 0) {
    item.sessions[sIdx].secs = secs;
  } else {
    item.sessions.push({ id: sessionId, secs, date: new Date().toISOString() });
  }

  item.time = Math.max(1, Math.round(item.sessions.reduce((a: number, s: any) => a + s.secs, 0) / 60));
  delete item._currentSecs;

  await videoQueueStorage.setValue([...queue]);
  try { browser.runtime.sendMessage({ action: 'QUEUE_UPDATED', count: queue.length }); } catch {}
}

async function removeFromQueue(url: string) {
  const clean = cleanUrl(url);
  const queue = await videoQueueStorage.getValue();
  const next = queue.filter(q => q.contentTitleEnglish !== clean);
  if (next.length !== queue.length) {
    await videoQueueStorage.setValue(next);
    try { browser.runtime.sendMessage({ action: 'QUEUE_UPDATED', count: next.length }); } catch {}
  }
}

// ── Modal ─────────────────────────────────────────────────────────────────────
function injectModalStyles() {
  if (document.getElementById('nt-modal-styles')) return;
  const style = document.createElement('style');
  style.id = 'nt-modal-styles';
  style.textContent = `
  #nt-modal-popup {
  z-index:2147483647;
  display:flex; align-items:center; justify-content:center;
  font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;
  cursor:default;
  }
  .nt-modal {
    background:#0d0d12; border:1px solid #222d42; border-radius:8px;
    width:320px; max-width:90vw; padding:20px; color:#dde4f0;
    box-shadow:0 10px 40px rgba(0,0,0,.8); box-sizing:border-box; color-scheme:dark;
  }
  .nt-modal-header {
    display:flex; align-items:center; gap:12px;
  }
  .nt-logo-sq {
    width:30px; height:30px; border:1px solid #F5B831; color:#F5B831;
    display:flex; align-items:center; justify-content:center;
    border-radius:4px; font-weight:bold; font-size:15px; box-sizing:border-box; flex-shrink:0;
  }
  .nt-title-area { display:flex; flex-direction:column; gap:4px; }
  .nt-brand-name { font-weight:bold; font-size:13px; letter-spacing:.5px; }
  .nt-badge {
    background:#3E1C1F; color:#E57373; border:1px solid #5A2A2E;
    font-size:9px; padding:2px 6px; border-radius:12px; font-weight:bold; width:max-content;
  }

  .nt-link-btn {
    background:none; border:none; color:#5a6a85; cursor:pointer;
    font-family:inherit; font-size:10px; font-weight:bold; padding:0; transition:color .2s;
  }
  .nt-link-btn:hover { color:#dde4f0; }
  .nt-link-btn.active { color:#F5B831; pointer-events:none; }

  .nt-form-group { display:flex; flex-direction:column; gap:6px; margin-bottom:14px; width:100%; box-sizing:border-box; }
  .nt-form-group label { color:#8A8A9A; font-size:11px; font-weight:bold; letter-spacing:.5px; }
  .nt-form-group input, .nt-form-group select {
    background:#14141e; border:1px solid #222d42; color:#fff; padding:8px 12px;
    border-radius:6px; font-family:inherit; font-size:12px; outline:none;
    transition:border .2s, background .2s; box-sizing:border-box; width:100%; min-width:0;
  }
  .nt-form-group input:focus, .nt-form-group select:focus { border-color:#F5B831; background:#1a1a24; }
  .nt-form-row { display:flex; gap:12px; width:100%; }
  .nt-form-row .nt-form-group { margin-bottom:0; }
  .nt-form-row .nt-form-group:first-child { flex:0 0 90px; }
  .nt-form-row .nt-form-group:last-child  { flex:1; min-width:0; }

  .nt-modal-footer { display:flex; gap:12px; margin-top:20px; }
  .nt-modal-opt { display:flex; align-items:center; gap:8px; margin-top:14px; font-size:11px; color:#a9b4c8; }
  .nt-modal-opt input[type="checkbox"] {
    -webkit-appearance:none;
    appearance:none;
    width:14px;
    height:14px;
    border-radius:999px;
    border:1px solid #222d42;
    background:#14141e;
    display:inline-grid;
    place-content:center;
    margin:0;
    cursor:pointer;
    flex:0 0 auto;
  }
  .nt-modal-opt input[type="checkbox"]::after {
    content:"";
    width:6px;
    height:3px;
    border-left:2px solid transparent;
    border-bottom:2px solid transparent;
    transform: rotate(-45deg);
    margin-top:-1px;
  }
  .nt-modal-opt input[type="checkbox"]:checked {
    background:#F5B831;
    border-color:#F5B831;
  }
  .nt-modal-opt input[type="checkbox"]:checked::after {
    border-left-color:#fff;
    border-bottom-color:#fff;
  }
  .nt-modal-opt label { cursor:pointer; user-select:none; }
  .nt-modal-footer button {
    flex:1; padding:10px; border:none; border-radius:4px; font-family:inherit;
    font-weight:bold; cursor:pointer; font-size:12px; transition:opacity .2s; box-sizing:border-box;
  }
  .nt-modal-footer button:hover { opacity:.8; }
  #nt-modal-cancel { background:#1E1E28; color:#A0A0B0; }
  #nt-modal-submit { background:#F5B831; color:#111; }
  .nt-absolute-pill { position:absolute; bottom:60px; left:20px; z-index:9999; }
  `;
  document.head.appendChild(style);
}

function localTodayISODate(): string {
  const d = new Date();
  d.setMinutes(d.getMinutes() - d.getTimezoneOffset());
  return d.toISOString().slice(0, 10);
}

function dateInputToISO(dateStr: string): string {
  const m = /^\s*(\d{4})-(\d{2})-(\d{2})\s*$/.exec(dateStr || '');
  if (!m) return new Date().toISOString();
  const year = Number(m[1]);
  const month = Number(m[2]);
  const day = Number(m[3]);

  // Keep local time-of-day to avoid timezone shifts.
  const now = new Date();
  const local = new Date(year, month - 1, day, now.getHours(), now.getMinutes(), 0, 0);
  return local.toISOString();
}

function showNTEditModal(badgeEl: HTMLElement, data: {
  channelName: string; videoTitle: string; url: string;
  totalSecs: number; showTotal: boolean; channelId: string | null;
  onToggleShowTotal: (v: boolean) => void;
}, onConfirm: (d: any) => void, onClose?: (submitted: boolean) => void) {
  injectModalStyles();

  // If already open, close it (toggle behavior)
  const existingPopup = document.getElementById('nt-modal-popup');
  if (existingPopup) {
    const closer = (existingPopup as any).__ntCloseModal as ((submitted: boolean) => void) | undefined;
    if (typeof closer === 'function') closer(false);
    else existingPopup.remove();
    return;
  }

  const popup = document.createElement('div');
  popup.id = 'nt-modal-popup';

  const today = localTodayISODate();
  const totalMins = Math.max(1, Math.round(data.totalSecs / 60));

  popup.innerHTML = `
  <div class="nt-modal">
  <div style="display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:16px;">
  <div class="nt-modal-header">
  <div class="nt-logo-sq">日</div>
  <div class="nt-title-area">
  <span class="nt-brand-name">NihongoAutoTracker</span>
  <span class="nt-badge">MANUAL LOG</span>
  </div>
  </div>
  </div>

  <div style="display:flex; justify-content:flex-start; gap:10px; font-size:10px; font-weight:bold; margin-bottom:16px;">
  <span style="color:#5a6a85;">DISPLAY:</span>
  <button id="nt-badge-session" class="nt-link-btn ${!data.showTotal ? 'active' : ''}">Session Only</button>
  <span style="color:#222d42;">/</span>
  <button id="nt-badge-total" class="nt-link-btn ${data.showTotal ? 'active' : ''}">Session / Total</button>
  </div>

  <div class="nt-form-group">
  <div style="display:flex; justify-content:space-between; align-items:flex-end;">
  <label>VIDEO TITLE</label>
  <span style="font-size:9px; color:#8A8A9A; max-width:140px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;" title="${data.channelName.replace(/"/g, '&quot;')}">${data.channelName.replace(/</g, '&lt;')}</span>
  </div>
  <input type="text" id="nt-edit-desc" value="${data.videoTitle.replace(/"/g, '&quot;')}"/>
  </div>

  <div class="nt-form-row">
  <div class="nt-form-group">
  <label>MINUTES</label>
  <input type="number" id="nt-edit-time" value="${totalMins}" min="1"/>
  </div>
  <div class="nt-form-group">
  <label>DATE</label>
  <input type="date" id="nt-edit-date" value="${today}"/>
  </div>
  </div>

  <div class="nt-modal-opt">
  <input type="checkbox" id="nt-clear-sessions" />
  <label for="nt-clear-sessions">Clear sessions with this log</label>
  </div>

  <div class="nt-modal-footer">
  <button id="nt-modal-cancel">Cancel</button>
  <button id="nt-modal-submit">Log Video</button>
  </div>
  </div>`;

  popup.addEventListener('click', e => e.stopPropagation());

  let closed = false;
  let closeListener: ((e: Event) => void) | null = null;
  const closeModal = (submitted: boolean) => {
    if (closed) return;
    closed = true;
    if (closeListener) {
      document.removeEventListener('click', closeListener);
      closeListener = null;
    }
    popup.remove();
    if (onClose) onClose(submitted);
  };

  (popup as any).__ntCloseModal = closeModal;

  // Append to document.body to escape overflow bounds of video players
  document.body.appendChild(popup);

  // Position it fixed to correctly overlay the badge position globally
  const rect = badgeEl.getBoundingClientRect();
  popup.style.position = 'fixed';
  popup.style.bottom = `${window.innerHeight - rect.top + 10}px`;
  popup.style.left = `${rect.left}px`;

  // Verify bounded layout right away
  requestAnimationFrame(() => {
    const popRect = popup.getBoundingClientRect();
    if (popRect.left < 0) popup.style.left = '10px';
    if (popRect.right > window.innerWidth) popup.style.left = `${window.innerWidth - popRect.width - 10}px`;
  });

  const btnSession = popup.querySelector('#nt-badge-session')!;
  const btnTotal = popup.querySelector('#nt-badge-total')!;

  btnSession.addEventListener('click', () => {
    btnSession.classList.add('active'); btnTotal.classList.remove('active');
    data.onToggleShowTotal(false);
  });
  btnTotal.addEventListener('click', () => {
    btnTotal.classList.add('active'); btnSession.classList.remove('active');
    data.onToggleShowTotal(true);
  });

  popup.querySelector('#nt-modal-cancel')!.addEventListener('click', () => closeModal(false));
  popup.querySelector('#nt-modal-submit')!.addEventListener('click', () => {
    const timeRaw = Number((popup.querySelector('#nt-edit-time') as HTMLInputElement).value);
    const timeVal = Math.max(1, Number.isFinite(timeRaw) ? timeRaw : 1);
    const dateRaw = (popup.querySelector('#nt-edit-date') as HTMLInputElement).value;
    const dateIso = dateRaw ? dateInputToISO(dateRaw) : new Date().toISOString();
    const clearSessions = !!(popup.querySelector('#nt-clear-sessions') as HTMLInputElement | null)?.checked;
    onConfirm({
      title: data.channelName,
      desc:  (popup.querySelector('#nt-edit-desc') as HTMLInputElement).value,
              time:  timeVal,
              date:  dateIso,
              clearSessions,
    });
    closeModal(true);
  });

  setTimeout(() => {
    closeListener = (e: Event) => {
      if (!popup.contains(e.target as Node) && !badgeEl.contains(e.target as Node)) {
        closeModal(false);
      }
    };
    document.addEventListener('click', closeListener);
  }, 0);
}

// ── Counter ───────────────────────────────────────────────────────────────────
let watchedSecs = 0;
let completedSessionSecs = 0;
let lastSyncSecs = 0;
let lastAutoCheckSecs = 0;
let _lastCounterPaint = 0;

function getTimestampContainer(vid: HTMLVideoElement): {el: HTMLElement; isFallback: boolean} | null {
  const host = window.location.hostname;
  if (host.includes('youtube.com')) {
    const el = document.querySelector('.ytp-left-controls') as HTMLElement;
    if (el) return { el, isFallback: false };
  }
  if (host.includes('crunchyroll.com')) {
    const el = document.querySelector('.vmp-controls__left') || document.querySelector('.velocity-controls');
    if (el) return { el: el as HTMLElement, isFallback: false };
  }
  if (host.includes('animekai')) {
    const el = document.querySelector('.plyr__controls__item.plyr__time--current') ||
    document.querySelector('.jw-controlbar-left-group');
    if (el) return { el: el as HTMLElement, isFallback: false };
  }
  const fallback = document.querySelector('.video-player-container') || document.querySelector('#movie_player') ||
  document.querySelector('.plyr__video-wrapper') || document.querySelector('.jw-media') || vid.parentElement;
  if (fallback) return { el: fallback as HTMLElement, isFallback: true };
  return null;
}

function ensureCounter(
  currentSecs: number,
  totalSecs: number,
  title: string,
  url: string,
  channelId: string | null,
  state: {hasTriggered: boolean; isManualLogging: boolean},
  vid: HTMLVideoElement,
  cfg: any,
  cachedChannelName: string,
  onReset: () => void
) {
  const shouldHide = cfg.hideButtons || (cfg.hideIfNotJapanese && !isLikelyJapaneseCached()) || (cfg.hideMusic && isMusic());
  let el = document.getElementById('nt-status-badge') as HTMLElement | null;
  if (shouldHide) { el?.remove(); return; }

  const multiSession = totalSecs > currentSecs + 2;
  const showTotal: boolean = cfg.showTotalInBadge ?? true;

  if (!el) {
    const containerData = getTimestampContainer(vid);
    if (!containerData) return;

    el = document.createElement('div');
    el.id = 'nt-status-badge';
    el.style.position = 'relative';
    el.style.cursor = 'pointer';
    if (containerData.isFallback) el.classList.add('nt-absolute-pill');

    el.innerHTML = `
    <div class="nt-pill-visual-wrapper">
    <span class="nt-brand-label">NT</span>
    <span class="nt-time-label">0:00</span>
    </div>`;

    el.onclick = async (e) => {
      // Prevents popup triggers if closing it indirectly through click
      if ((e.target as HTMLElement).closest('#nt-modal-popup')) return;

      // Toggle: if modal is open, close it.
      const existingPopup = document.getElementById('nt-modal-popup');
      if (existingPopup) {
        const closer = (existingPopup as any).__ntCloseModal as ((submitted: boolean) => void) | undefined;
        if (typeof closer === 'function') closer(false);
        else existingPopup.remove();
        return;
      }

      if (state.isManualLogging) return;
      state.isManualLogging = true;

      const liveCfg = await configStorage.getValue() as any;
      const liveShowTotal = liveCfg.showTotalInBadge ?? true;
      const channelName = cachedChannelName || getChannelNameFallback();

      showNTEditModal(
        el!,
        {
          channelName, videoTitle: title, url, totalSecs, showTotal: liveShowTotal, channelId,
          onToggleShowTotal: async (v) => {
            const c = await configStorage.getValue() as any;
            await configStorage.setValue({ ...c, showTotalInBadge: v });
          },
        },
        async final => {
          try {
            state.hasTriggered = true;
            const mediaData = await getChannelMediaData(channelId, final.title);
            const ok = await submitLog({
              type: "video",
              mediaId: channelId || "web-video",
              description: final.desc,
              mediaData,
              episodes: 0,
              time: Math.floor(final.time),
                                       pages: 0,
                                       date: final.date || new Date().toISOString(),
                                       unknownDate: false
            });

            if (ok) {
              if (final.clearSessions) {
                await removeFromQueue(url);
                onReset();
              } else {
                state.hasTriggered = false;
              }
            } else {
              state.hasTriggered = false;
            }
          } catch (err) {
            state.hasTriggered = false;
          }
        },
        (submitted) => {
          state.isManualLogging = false;
          if (!submitted) state.hasTriggered = false;
        }
      );
    };

    containerData.el.appendChild(el);
  }

  const now = performance.now();
  if (now - _lastCounterPaint < 1000) return;
  _lastCounterPaint = now;

  const timeLabel = el.querySelector<HTMLElement>('.nt-time-label')!;
  const currentStr = fmtSecs(currentSecs);

  if (multiSession && showTotal) {
    const totalStr = fmtSecs(totalSecs);
    timeLabel.textContent = `${currentStr} / ${totalStr}`;
  } else {
    timeLabel.textContent = currentStr;
  }

  el.title = 'Log this video manually';
}

// ── Main ──────────────────────────────────────────────────────────────────────
export default defineContentScript({
  matches:['*://*.youtube.com/*','*://music.youtube.com/*','*://*.crunchyroll.com/*','*://*.animekai.to/*'],
  cssInjectionMode: 'manifest',

  async main() {
    let cachedConfig: any = await configStorage.getValue() || {};

    watchedSecs = 0;
    lastSyncSecs = 0;
    lastAutoCheckSecs = 0;
    completedSessionSecs = 0;
    let currentSessionId = crypto.randomUUID();
    const state = { hasTriggered: false, isManualLogging: false };
    let trackedVideo: HTMLVideoElement | null = null;
    let currentUrl = '';
    let channelId: string | null = null;
    let cachedChannelName = '';
    let playClockStart = -1;

    function flushPlayClock() {
      if (playClockStart < 0) return;
      const elapsed = (performance.now() - playClockStart) / 1000;
      playClockStart = -1;
      if (elapsed > 0 && elapsed < 7200) watchedSecs += elapsed;
    }

    const getLiveWatched = () =>
    watchedSecs + (playClockStart >= 0 ? (performance.now() - playClockStart) / 1000 : 0);

    const getTotal = () => completedSessionSecs + getLiveWatched();

    const resetSession = () => {
      flushPlayClock();
      watchedSecs = 0;
      completedSessionSecs = 0;
      lastSyncSecs = 0;
      lastAutoCheckSecs = 0;
      currentSessionId = crypto.randomUUID();
      state.hasTriggered = false;
      state.isManualLogging = false;
      if (trackedVideo && !trackedVideo.paused && !trackedVideo.ended && trackedVideo.readyState > 2) {
        playClockStart = performance.now();
      } else {
        playClockStart = -1;
      }
      const badgeLabel = document.querySelector('#nt-status-badge .nt-time-label');
      if (badgeLabel) badgeLabel.textContent = "0:00";
    };

      const attach = (vid: HTMLVideoElement) => {
        const cleanedHref = cleanUrl(window.location.href);
        if (trackedVideo === vid && currentUrl === cleanedHref) return;

        flushPlayClock();
        if (trackedVideo && watchedSecs >= 60 && currentUrl && !state.hasTriggered) {
          finalizeSession(watchedSecs, currentUrl, currentSessionId);
        }

        trackedVideo     = vid;
        currentUrl       = cleanedHref;
        watchedSecs      = 0;
        playClockStart   = -1;
        lastSyncSecs     = 0;
        lastAutoCheckSecs = 0;
        state.hasTriggered = false;
        state.isManualLogging = false;
        channelId        = null;
        cachedChannelName = '';
        completedSessionSecs = 0;
        currentSessionId = crypto.randomUUID();
        invalidateJpCache();
        _lastCounterPaint = 0;
        document.getElementById('nt-status-badge')?.remove();

        const tryChannel = () => {
          if (!channelId) { const id = getYouTubeChannelId(); if (id) channelId = id; }
          if (!cachedChannelName) { const n = getChannelNameFallback(); if (n) cachedChannelName = n; }
        };
        tryChannel(); setTimeout(tryChannel, 2000); setTimeout(tryChannel, 5000); setTimeout(tryChannel, 10000);

        (async () => {
          const queue = await videoQueueStorage.getValue();
          const existing = queue.find(q => q.contentTitleEnglish === currentUrl) as any;
          if (existing) {
            const sessions: any[] = existing.sessions ||[];
            completedSessionSecs = sessions.reduce((a: number, s: any) => a + s.secs, 0);
          }
        })();

        if (!vid.paused && !vid.ended && vid.readyState > 2) {
          playClockStart = performance.now();
        }

        vid.addEventListener('playing', () => {
          playClockStart = performance.now();
        });

        vid.addEventListener('play', () => {
          playClockStart = performance.now();
          if (vid.currentTime < 5) state.hasTriggered = false;
        });

          const stopClock = () => { flushPlayClock(); };
          vid.addEventListener('pause',   stopClock);
          vid.addEventListener('waiting', stopClock);
          vid.addEventListener('seeking', stopClock);

          vid.addEventListener('seeked', () => {
            if (vid.currentTime < 5) state.hasTriggered = false;
            if (!vid.paused && !vid.ended) playClockStart = performance.now();
          });

            vid.addEventListener('timeupdate', async () => {
              const cfg = cachedConfig;

              if (!state.hasTriggered) {
                ensureCounter(getLiveWatched(), getTotal(), document.title, currentUrl, channelId, state, vid, cfg, cachedChannelName, resetSession);
              }

              if (state.hasTriggered || vid.duration <= 0) return;
              if (state.isManualLogging) return;

              const autoOn = cfg.autoSend ?? (cfg.logMode === 'auto');
              const liveSecs = getLiveWatched();

              if (!autoOn && reachedQueueThreshold(cfg, liveSecs, vid) && (liveSecs - lastSyncSecs) >= 10) {
                lastSyncSecs = liveSecs;
                if (isLikelyJapaneseCached() && !isMusic()) {
                  await upsertQueueLive(liveSecs, document.title, cachedChannelName || getChannelNameFallback(), currentUrl, channelId, currentSessionId);
                }
              }

              if (autoOn && (liveSecs - lastAutoCheckSecs) >= 5) {
                lastAutoCheckSecs = liveSecs;
                if (isLikelyJapaneseCached() && !isMusic()) {
                  const threshType  = cfg.thresholdType  ?? 'percent';
                  const threshValue = cfg.thresholdValue ?? cfg.threshold ?? 95;
                  const triggered   = threshType === 'percent'
                  ? (vid.currentTime / vid.duration) * 100 >= threshValue
                  : (liveSecs / 60) >= threshValue;
                  if (triggered) {
                    state.hasTriggered = true;

                    const sessionMins = Math.max(1, Math.round(liveSecs / 60));
                    const mediaData = await getChannelMediaData(channelId, cachedChannelName || getChannelNameFallback());

                    const ok = await submitLog({
                      type: 'video',
                      mediaId: channelId || 'web-video',
                      description: document.title,
                      mediaData,
                      time: sessionMins,
                      date: new Date().toISOString(),
                                               private: false,
                                                 episodes: 0,
                                                 pages: 0,
                                                 unknownDate: false
                    });

                    if (ok) {
                      removeFromQueue(currentUrl);
                      resetSession();
                    } else {
                      state.hasTriggered = false;
                    }
                  }
                }
              }
            });

            vid.addEventListener('ended', async () => {
              flushPlayClock();
              if (state.hasTriggered) return;
              const cfg = cachedConfig;
              const autoOn = cfg.autoSend ?? (cfg.logMode === 'auto');
              if (!autoOn && isLikelyJapaneseCached() && !isMusic() && reachedQueueThreshold(cfg, watchedSecs, vid)) {
                await finalizeSession(watchedSecs, currentUrl, currentSessionId);
                completedSessionSecs += watchedSecs;
                watchedSecs = 0;
                currentSessionId = crypto.randomUUID();
              }
            });

            vid.addEventListener('emptied', async () => {
              flushPlayClock();
              const urlNow = cleanUrl(window.location.href);
              if (urlNow !== currentUrl) {
                if (!state.hasTriggered && watchedSecs >= 1 && isLikelyJapaneseCached() && !isMusic()) {
                  await finalizeSession(watchedSecs, currentUrl, currentSessionId);
                }
                watchedSecs = 0;
                lastSyncSecs = 0;
                lastAutoCheckSecs = 0;
                state.hasTriggered = false;
                document.getElementById('nt-status-badge')?.remove();
              }
            });
      };

      browser.storage.onChanged.addListener((changes, area) => {
        if (area === 'local' && changes['config']) {
          configStorage.getValue().then(c => {
            if(c) {
              cachedConfig = c;
              const badge = document.getElementById('nt-status-badge');
              if (badge) {
                const shouldHide = c.hideButtons || (c.hideIfNotJapanese && !isLikelyJapaneseCached()) || (c.hideMusic && isMusic());
                if (shouldHide) badge.remove();
              }
            }
          });
        }

        if (area === 'local' && changes['videoQueue']) {
          const queue = Array.isArray(changes['videoQueue'].newValue) ? changes['videoQueue'].newValue : [];
        const clean = cleanUrl(window.location.href);
        const exists = queue.some((q: any) => q.contentTitleEnglish === clean);
        if (!exists) {
          completedSessionSecs = 0;
          watchedSecs = 0;
          lastSyncSecs = 0;
          lastAutoCheckSecs = 0;
          state.hasTriggered = false;

          if (!trackedVideo?.paused && !trackedVideo?.ended && (trackedVideo?.readyState ?? 0) > 2) {
            playClockStart = performance.now();
          }

          const badgeLabel = document.querySelector('#nt-status-badge .nt-time-label');
          if (badgeLabel) badgeLabel.textContent = "0:00";
        }
      }
    });

    setInterval(async () => {
      const vid = document.querySelector<HTMLVideoElement>('video');
      if (vid) {
        attach(vid);
        if (!state.hasTriggered) {
          const cfg = cachedConfig;
          ensureCounter(getLiveWatched(), getTotal(), document.title, currentUrl, channelId, state, vid, cfg, cachedChannelName, resetSession);
        }
      }
    }, 2000);
  },
});
