import { JP_RE } from '@/lib/constants';
import type { TrackerConfig, VideoSiteAdapter } from '@/lib/types';
import { getChannelNameFallback, getYouTubeChannelId } from '@/lib/utils/youtube-extraction';

function getLivePlayerResponse(): any {
  if (typeof document === 'undefined') return null;
  let attr = document.documentElement.getAttribute('data-yt-player-response');
  if (!attr) {
    window.dispatchEvent(new CustomEvent('nat-request-player-response'));
    attr = document.documentElement.getAttribute('data-yt-player-response');
  }
  if (attr) {
    try {
      return JSON.parse(attr);
    } catch (e) { }
  }
  return null;
}

export const youtubeAdapter: VideoSiteAdapter = {
  name: 'YouTube',
  matchPatterns: [
    '*://*.youtube.com/*',
    '*://music.youtube.com/*',
  ],

  isEnabled(_config: TrackerConfig): boolean {
    return true;
  },

  getChannelId: getYouTubeChannelId,
  getChannelName: getChannelNameFallback,

  isMusic(): boolean {
    const host = window.location.hostname;
    if (host === 'music.youtube.com') return true;

    if (host.includes('youtube.com')) {
      const isLive = !!document.querySelector('.ytp-live, .re-live-badge, [is-live]');
      const hasMusicMetadata = !!document.querySelector('ytd-structured-description-content-renderer');
      const playerResponse = getLivePlayerResponse();
      const isMusicCategory = playerResponse?.videoDetails?.categoryId === '10';

      if (isLive) return hasMusicMetadata;
      if (isMusicCategory) return true;

      const g = document.querySelector('meta[itemprop="genre"]');
      if (g?.getAttribute('content') === 'Music') return true;
      if (document.querySelector('ytd-music-watch-metadata-renderer')) return true;

      const secondaryInfo =
        (document.querySelector('ytd-video-secondary-info-renderer') as HTMLElement | null)?.innerText || '';
      if (secondaryInfo.includes('Auto-generated by YouTube') || secondaryInfo.includes('Provided to YouTube'))
        return true;
    }
    return false;
  },

  isLikelyJapanese(): boolean {
    const host = window.location.hostname;

    if (host.includes('youtube.com')) {
      try {
        const playerResponse = getLivePlayerResponse();
        const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (tracks) {
          for (const track of tracks) if (track.languageCode === 'ja') return true;
        }
      } catch (_e) { }

      const docTitle = document.title.replace(/^\(\d+\)\s*/, '');
      if ((docTitle.match(JP_RE) ?? []).length >= 1) return true;

      const titleEl = document.querySelector<HTMLElement>('#title h1 yt-formatted-string, h1.ytd-watch-metadata');
      if (titleEl && (titleEl.innerText.match(JP_RE) ?? []).length >= 1) return true;

      const channelEl = document.querySelector<HTMLElement>(
        '#owner ytd-channel-name yt-formatted-string, ytd-channel-name a',
      );
      if (channelEl && (channelEl.innerText.match(JP_RE) ?? []).length >= 1) return true;

      const descEl = document.querySelector<HTMLElement>(
        '#description-inline-expander yt-attributed-string, ytd-expandable-video-description-body-renderer',
      );
      if (descEl) {
        const sample = descEl.innerText?.slice(0, 1000) ?? '';
        if ((sample.match(JP_RE) ?? []).length >= 3) return true;
      }
    }
    return false;
  },

  getTimestampContainer(vid: HTMLVideoElement): HTMLElement | null {
    const host = window.location.hostname;
    if (host.includes('youtube.com')) {
      const el = document.querySelector('.ytp-left-controls') as HTMLElement;
      if (el) return el;
    }
    const fallback = document.querySelector('.video-player-container') || document.querySelector('#movie_player') || document.querySelector('.plyr__video-wrapper') || document.querySelector('.jw-media') || vid.parentElement;
    if (fallback) return fallback as HTMLElement;
    return null;
  },

  isAdPlaying(doc: Document): boolean {
    const host = window.location.hostname;
    if (host.includes('youtube.com')) {
      return !!doc.querySelector(
        '.ad-showing, .ad-interrupting, .html5-video-player.ad-showing, .html5-video-player.ad-interrupting'
      );
    }
    return false;
  },

  getPlaylistContainers(doc: Document): HTMLElement[] {
    const classicSel = 'ytd-playlist-header-renderer .metadata-buttons-wrapper';
    const modernHeaderSel = 'yt-page-header-renderer yt-flexible-actions-view-model, yt-page-header-view-model yt-flexible-actions-view-model, yt-page-header-renderer ytd-menu-renderer, ytd-playlist-header-renderer ytd-menu-renderer';
    const panelSel = 'ytd-playlist-panel-renderer #playlist-action-menu #top-level-buttons-computed';

    const containers: HTMLElement[] = [];
    const selectors = `${classicSel}, ${modernHeaderSel}, ${panelSel}`;
    const matches = doc.querySelectorAll(selectors);

    for (let i = 0; i < matches.length; i++) {
      const el = matches[i];
      if (el instanceof HTMLElement) {
        if (el.offsetWidth > 0 || el.offsetHeight > 0) {
          containers.push(el);
        }
      }
    }
    return containers;
  },

  injectPlaylistButton(container: HTMLElement, btn: HTMLButtonElement): void {
    const overflowNode = container.querySelector('yt-button-view-model:last-child, ytd-menu-renderer:last-child, button:last-child, [class*="button"]:last-child');
    if (overflowNode && overflowNode.parentElement === container) {
      container.insertBefore(btn, overflowNode);
    } else {
      container.appendChild(btn);
    }
  }
};
