import { JP_RE } from '@/lib/constants';
import type { TrackerConfig, VideoSiteAdapter } from '@/lib/types';
import { stripVideoTitle } from '@/lib/utils/text-parsing';
import { cleanUrl } from '@/lib/utils/url';
import { getChannelNameFallback, getVerifiedWatchRoot, getYouTubeChannelId } from '@/lib/utils/youtube-extraction';
import {
  getPlayerSnapshot,
  getYouTubeVideoId,
  type YouTubePlayerSnapshot,
} from '@/lib/utils/youtube-player-response';

const MUSIC_HOST = 'music.youtube.com';
const MUSIC_CATEGORY = 'Music';

const MUSIC_TITLE_PATTERNS = [
  /\b(official music video|music video|lyric video|official mv|official audio)\b/i,
  /【mv】|\[mv\]/i,
  /\bmv\b/i,
  /(ノンクレジット|アニメ)?(op|ed)(映像|ムービー)/i,
];

/** Live streams that present themselves as background music rather than talk. */
const LIVE_MUSIC_TITLE_RE = /\b(24\/7|radio|lo-?fi|bgm|playlist)\b|作業用|睡眠用|勉強用/i;

export type SpokenLanguage = 'japanese' | 'other' | 'unknown';

/** Everything the language / music rules look at, from whichever source could be trusted. */
export interface VideoFacts {
  title: string;
  author: string;
  description: string;
  category: string;
  isLiveNow: boolean;
  spokenLanguage: SpokenLanguage;
}

function countJapanese(text: string | null | undefined): number {
  return text ? (text.match(JP_RE) ?? []).length : 0;
}

function isJapaneseLanguageCode(code: string): boolean {
  const lang = code.toLowerCase();
  return lang === 'ja' || lang.startsWith('ja-');
}

/**
 * The language YouTube itself attributes to the audio, when it exposes one.
 *
 * The auto-generated caption track is produced from the audio, so its language
 * is the spoken language. Uploaded caption tracks say nothing on their own: a
 * Japanese track on a foreign video is a translation.
 */
export function getSpokenLanguage(snapshot: YouTubePlayerSnapshot): SpokenLanguage {
  const autoGenerated = snapshot.captionTracks.find((track) => track.kind === 'asr');
  if (autoGenerated?.languageCode) {
    return isJapaneseLanguageCode(autoGenerated.languageCode) ? 'japanese' : 'other';
  }
  if (snapshot.defaultAudioLanguage) {
    return isJapaneseLanguageCode(snapshot.defaultAudioLanguage) ? 'japanese' : 'other';
  }
  const tracks = snapshot.captionTracks;
  if (tracks.length === 1 && isJapaneseLanguageCode(tracks[0].languageCode)) return 'japanese';
  return 'unknown';
}

export function isJapaneseContent(facts: VideoFacts): boolean {
  if (facts.spokenLanguage !== 'unknown') return facts.spokenLanguage === 'japanese';

  // No audio-language signal: fall back to the script used by the uploader.
  return countJapanese(facts.title) >= 1
    || countJapanese(facts.author) >= 1
    || countJapanese(facts.description.slice(0, 1000)) >= 3;
}

export function isMusicContent(facts: VideoFacts): boolean {
  const musicalTitle = MUSIC_TITLE_PATTERNS.some((pattern) => pattern.test(facts.title));

  if (facts.isLiveNow) {
    // A live stream filed under "Music" is usually a talk or karaoke stream.
    // It only counts as music when it also presents itself as a music feed.
    return facts.category === MUSIC_CATEGORY && (musicalTitle || LIVE_MUSIC_TITLE_RE.test(facts.title));
  }

  if (facts.category === MUSIC_CATEGORY || musicalTitle) return true;

  // Art tracks distributed by labels
  return facts.description.includes('Auto-generated by YouTube') || facts.description.includes('Provided to YouTube');
}

function factsFromSnapshot(snapshot: YouTubePlayerSnapshot): VideoFacts {
  return {
    title: snapshot.title,
    author: snapshot.author,
    description: snapshot.description,
    category: snapshot.category,
    isLiveNow: snapshot.isLiveNow,
    spokenLanguage: getSpokenLanguage(snapshot),
  };
}

/**
 * Fallback for when the player snapshot is unavailable. Returns null while the
 * page still renders the previous video, so callers report "unknown" instead of
 * judging the new video by the old one's metadata.
 */
function factsFromDom(videoId: string | null): VideoFacts | null {
  const root = getVerifiedWatchRoot(videoId);
  if (!root && videoId && document.querySelector('ytd-watch-flexy')) return null;

  const text = (selector: string) => root?.querySelector(selector)?.textContent?.trim() ?? '';

  // Server-rendered microdata describes the first video loaded in this tab only.
  const microdataId = document.querySelector('meta[itemprop="identifier"]')?.getAttribute('content');
  const microdataGenre = videoId && microdataId === videoId
    ? document.querySelector('meta[itemprop="genre"]')?.getAttribute('content') ?? ''
    : '';
  const category = root?.querySelector('ytd-music-watch-metadata-renderer') ? MUSIC_CATEGORY : microdataGenre;

  return {
    title: text('#title h1 yt-formatted-string, h1.ytd-watch-metadata') || stripVideoTitle(document.title),
    author: text('#owner ytd-channel-name yt-formatted-string, #owner ytd-channel-name a'),
    description: text(
      '#description-inline-expander yt-attributed-string, ytd-expandable-video-description-body-renderer',
    ).slice(0, 1500),
    category,
    isLiveNow: !!document.querySelector('#movie_player .ytp-live'),
    spokenLanguage: 'unknown',
  };
}

function getVideoFacts(): VideoFacts | null {
  const videoId = getYouTubeVideoId();
  const snapshot = getPlayerSnapshot(videoId);
  return snapshot ? factsFromSnapshot(snapshot) : factsFromDom(videoId);
}

function watchUrl(videoId: string): string {
  return `https://www.youtube.com/watch?v=${videoId}`;
}

export const youtubeAdapter: VideoSiteAdapter = {
  name: 'YouTube',
  matchPatterns: [
    '*://*.youtube.com/*',
    '*://music.youtube.com/*',
  ],

  isEnabled(_config: TrackerConfig): boolean {
    return true;
  },

  getChannelId: getYouTubeChannelId,
  getChannelName: getChannelNameFallback,

  isMusic(): boolean {
    const host = window.location.hostname;
    if (host === MUSIC_HOST) return true;
    if (!host.includes('youtube.com')) return false;

    const facts = getVideoFacts();
    return !!facts && isMusicContent(facts);
  },

  isLikelyJapanese(): boolean {
    if (!window.location.hostname.includes('youtube.com')) return false;

    const facts = getVideoFacts();
    return !!facts && isJapaneseContent(facts);
  },

  isLive(): boolean {
    return getVideoFacts()?.isLiveNow ?? false;
  },

  getVideoTitle(): string {
    return getPlayerSnapshot()?.title ?? '';
  },

  getTrackingUrl(vid: HTMLVideoElement): string | null {
    // YouTube Music keeps playing while its URL moves between pages; it is keyed as before.
    if (window.location.hostname === MUSIC_HOST) return cleanUrl(window.location.href);

    // Hover previews play in their own player; only the main one is "the video".
    const mainPlayer = document.getElementById('movie_player');
    if (mainPlayer && !mainPlayer.contains(vid)) return null;

    if (window.location.pathname.startsWith('/shorts/')) return null;

    const videoId = getYouTubeVideoId();
    if (videoId) return watchUrl(videoId);

    // Miniplayer: the main player keeps playing after leaving the watch page.
    if (mainPlayer?.closest('ytd-miniplayer')) {
      const playing = getPlayerSnapshot(null);
      if (playing) return watchUrl(playing.videoId);
    }
    return null;
  },

  getTimestampContainer(vid: HTMLVideoElement): HTMLElement | null {
    const host = window.location.hostname;
    if (host.includes('youtube.com')) {
      const el = document.querySelector('.ytp-left-controls') as HTMLElement;
      if (el) return el;
    }
    const fallback = document.querySelector('.video-player-container') || document.querySelector('#movie_player') || document.querySelector('.plyr__video-wrapper') || document.querySelector('.jw-media') || vid.parentElement;
    if (fallback) return fallback as HTMLElement;
    return null;
  },

  isAdPlaying(doc: Document): boolean {
    const host = window.location.hostname;
    if (host.includes('youtube.com')) {
      return !!doc.querySelector(
        '.ad-showing, .ad-interrupting, .html5-video-player.ad-showing, .html5-video-player.ad-interrupting'
      );
    }
    return false;
  },

  getPlaylistContainers(doc: Document): HTMLElement[] {
    const classicSel = 'ytd-playlist-header-renderer .metadata-buttons-wrapper';
    const modernHeaderSel = 'yt-page-header-renderer yt-flexible-actions-view-model, yt-page-header-view-model yt-flexible-actions-view-model, yt-page-header-renderer ytd-menu-renderer, ytd-playlist-header-renderer ytd-menu-renderer';
    const panelSel = 'ytd-playlist-panel-renderer #playlist-action-menu #top-level-buttons-computed';

    const containers: HTMLElement[] = [];
    const selectors = `${classicSel}, ${modernHeaderSel}, ${panelSel}`;
    const matches = doc.querySelectorAll(selectors);

    for (let i = 0; i < matches.length; i++) {
      const el = matches[i];
      if (el instanceof HTMLElement) {
        if (el.offsetWidth > 0 || el.offsetHeight > 0) {
          containers.push(el);
        }
      }
    }
    return containers;
  },

  injectPlaylistButton(container: HTMLElement, btn: HTMLButtonElement): void {
    const overflowNode = container.querySelector('yt-button-view-model:last-child, ytd-menu-renderer:last-child, button:last-child, [class*="button"]:last-child');
    if (overflowNode && overflowNode.parentElement === container) {
      container.insertBefore(btn, overflowNode);
    } else {
      container.appendChild(btn);
    }
  }
};
