import { JP_RE } from '@/lib/constants';
import type { TrackerConfig, VideoSiteAdapter } from '@/lib/types';
import { getChannelNameFallback, getYouTubeChannelId } from '@/lib/utils/youtube-extraction';

export const youtubeAdapter: VideoSiteAdapter = {
  name: 'YouTube',
  matchPatterns: [
    '*://*.youtube.com/*',
    '*://music.youtube.com/*',
    '*://*.crunchyroll.com/*',
    '*://*.animekai.to/*',
  ],

  isEnabled(_config: TrackerConfig): boolean {
    return true;
  },

  getChannelId: getYouTubeChannelId,
  getChannelName: getChannelNameFallback,

  isMusic(): boolean {
    const host = window.location.hostname;
    if (host === 'music.youtube.com') return true;

    if (host.includes('youtube.com')) {
      const isLive = !!document.querySelector('.ytp-live, .re-live-badge, [is-live]');
      const hasMusicMetadata = !!document.querySelector('ytd-structured-description-content-renderer');
      const playerResponse = (window as any).ytInitialPlayerResponse;
      const isMusicCategory = playerResponse?.videoDetails?.categoryId === '10';

      if (isLive) return hasMusicMetadata;
      if (isMusicCategory) return true;

      const g = document.querySelector('meta[itemprop="genre"]');
      if (g?.getAttribute('content') === 'Music') return true;
      if (document.querySelector('ytd-music-watch-metadata-renderer')) return true;

      const secondaryInfo =
        (document.querySelector('ytd-video-secondary-info-renderer') as HTMLElement | null)?.innerText || '';
      if (secondaryInfo.includes('Auto-generated by YouTube') || secondaryInfo.includes('Provided to YouTube'))
        return true;
    }
    return false;
  },

  isLikelyJapanese(): boolean {
    const host = window.location.hostname;

    /* Known Japanese content sites → always true */
    if (host.includes('animekai') || host.includes('crunchyroll')) return true;

    if (host.includes('youtube.com')) {
      /* Check for Japanese caption tracks in player response */
      try {
        const playerResponse = (window as any).ytInitialPlayerResponse;
        const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (tracks) {
          for (const track of tracks) if (track.languageCode === 'ja') return true;
        }
      } catch (_e) { /* caption data not available */ }

      /* Check document title for Japanese characters */
      const docTitle = document.title.replace(/^\(\d+\)\s*/, '');
      if ((docTitle.match(JP_RE) ?? []).length >= 1) return true;

      /* Check video title element */
      const titleEl = document.querySelector<HTMLElement>('#title h1 yt-formatted-string, h1.ytd-watch-metadata');
      if (titleEl && (titleEl.innerText.match(JP_RE) ?? []).length >= 1) return true;

      /* Check channel name */
      const channelEl = document.querySelector<HTMLElement>(
        '#owner ytd-channel-name yt-formatted-string, ytd-channel-name a',
      );
      if (channelEl && (channelEl.innerText.match(JP_RE) ?? []).length >= 1) return true;

      /* Sample the video description for Japanese text */
      const descEl = document.querySelector<HTMLElement>(
        '#description-inline-expander yt-attributed-string, ytd-expandable-video-description-body-renderer',
      );
      if (descEl) {
        const sample = descEl.innerText?.slice(0, 1000) ?? '';
        if ((sample.match(JP_RE) ?? []).length >= 3) return true;
      }
    }
    return false;
  },

  getTimestampContainer(vid: HTMLVideoElement): HTMLElement | null {
    const host = window.location.hostname;
    if (host.includes('youtube.com')) {
      const el = document.querySelector('.ytp-left-controls') as HTMLElement;
      if (el) return el;
    }
    if (host.includes('crunchyroll.com')) {
      const el = document.querySelector('.vmp-controls__left') || document.querySelector('.velocity-controls');
      if (el) return el as HTMLElement;
    }
    if (host.includes('animekai')) {
      const el = document.querySelector('.plyr__controls__item.plyr__time--current') || document.querySelector('.jw-controlbar-left-group');
      if (el) return el as HTMLElement;
    }
    const fallback = document.querySelector('.video-player-container') || document.querySelector('#movie_player') || document.querySelector('.plyr__video-wrapper') || document.querySelector('.jw-media') || vid.parentElement;
    if (fallback) return fallback as HTMLElement;
    return null;
  }
};
